utils::globalVariables(
  c(
    "CNTR_ID",
    "database",
    "databasex",
    "Department",
    "code",
    "DOI",
    "extension",
    "id",
    "ifn",
    "ifnx",
    "ISO3_CODE",
    "lat",
    "layer",
    "layer_shrt",
    "Letter",
    "lon",
    "mfe50_provinces",
    "NAME",
    "NAME_ENGL",
    "Number",
    "province",
    "Species",
    "TABLE_NAME",
    "TABLE_TYPE",
    "url_field_db",
    "url_sig_db",
    "Version",
    "Year",
    "year",
    ".",
    "species_name", "small_density", "small_h_dm", "NumPies", "Hm",
    "big_h_dm", "small_density_ha", "big_density_ha", "Estadillo",
    "Fcc", "agent_name", "h_dm", "nArbol", "OrdenIf4", "OrdenIf3",
    "d_mm", "Ht", "Hcopa", "OrdenIf2", "tree_id", "data_lst",
    "Dn1", "Dn2", "Ordenif3", "Diametro1", "Diametro2", "NumOrden",
    "Altura", "h_m", "Provincia", "province_fix", "geometry",
    "dclass", "n", "h_mean", "n_ha", "g_ha", "CoorX",

    ".cumtrees", ".do", ".nmax", "d", "h", "nt"
  ))
